###
POST http://localhost:5200/auth/signup
Content-Type: application/json

{
 "username":"Tester",
 "password":"chopsticks"
} 
###
POST http://localhost:5200/auth/login
Content-Type: application/json

{
 "username":"Tester",
 "password":"chopsticks"
} 
