###
POST http://localhost:5200/auth/signup
Content-Type: application/json

{
 "username":"kankan",
 "password":"isgoated"
} 
###
POST http://localhost:5200/auth/login
Content-Type: application/json

{
 "username":"seki",
 "password":"codex"
} 
